---
title: "README"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview

This R package contains functions that I use often to create plots. 

At the moment, there's just `theme_carly_presents()`, which simplifies `ggplot2::theme_bw()` a bit for a low-resolution format like presentations. 

# Installation

```
devtools::install_github("carlislerainey/ggcarly")
```

# Examples

## Latent Dissent

```{r latent-dissent, fig.height=4, fig.path="figs/", fig.width=8, message=FALSE}
# load packages
library(tidyverse)
library(ggcarly)

# load latent dissent data
dissent_df <- read_csv("https://raw.githubusercontent.com/carlislerainey/latent-dissent/master/latent-dissent.csv") %>% 
  glimpse()

# plot eta
p <- ggplot(dissent_df, aes(x = year, y = eta, group = ccode)) + 
  geom_line(alpha = 0.2) + 
  theme_carly_presents()
p + geom_line(data = filter(dissent_df, country_name %in% c("United States", "Canada", "Mexico", "Russia")),
              aes(x = year, y = eta, color = country_name), alpha = 1, size = 2) + 
  scale_color_brewer(type = "qual", palette = 2) + 
  labs(title = "A Latent Measure of Dissent",
       x = "Year",
       y = "Dissent",
       color = "Country")

```

## Scatterplot

```{r scatterplot, fig.height=3.5, fig.path="figs/", fig.width=8}
# load packages
library(ggplot2)
library(ggcarly)

# scatterplot
ggplot(mtcars, aes(wt, mpg, size = hp)) + 
  geom_point(shape = 21) + 
  labs(x = "Weight (1000 lbs.)",
       y = "Miles Per Gallon",
       size = "Gross Horsepower") + 
  theme_carly_presents()
```

## Bar Plot

```{r bar-plot, fig.height=3.5, fig.path="figs/", fig.width=6}
# load packages
library(ggplot2)
library(ggcarly)

# barplot
ggplot(mpg, aes(class)) + 
  geom_bar() + 
  coord_flip() + 
  theme_carly_presents()
```

## Facetted Scatterplot

```{r facetted-scatterplot, fig.height=7, fig.path="figs/", fig.width=8}
# load packages
library(ggplot2)
library(ggcarly)

# facetted scatterplot
ggplot(mpg, aes(displ, hwy)) + 
  geom_point() + 
  facet_wrap(vars(class)) + 
  theme_carly_presents()
```

## Histogram

```{r histogram, fig.height=3, fig.path="figs/", fig.width=4}
# load packages
library(ggplot2)
library(ggcarly)

# dotplot
ggplot(mtcars, aes(x = mpg)) + 
  geom_histogram(bins = 10) + 
  theme_carly_presents()
```
